apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {} # Das temporäre gemeinsame Volume
      containers:
        - name: writer
          image: oezkan00/log-output:v1.2
          env:
            - name: MODE
              value: "WRITE"
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
        - name: reader
          image: oezkan00/log-output:v1.2
          env:
            - name: MODE
              value: "READ"
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
