apiVersion: v1
kind: Service
metadata:
  name: todo-db-svc
  namespace: project
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: todo-db
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-db-ss
  namespace: project
spec:
  serviceName: todo-db-svc
  replicas: 1
  selector:
    matchLabels:
      app: todo-db
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_PASSWORD
              value: "todo-pass-123"
            - name: POSTGRES_DB
              value: "todo_db"
          volumeMounts:
            - name: todo-db-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: todo-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 500Mi
